@startuml

title __SOILCORRECTION's Class Diagram__\n

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    interface edu.utfpr.cp.dacom.sa.soilcorrection.Conversao.Conversao {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    class edu.utfpr.cp.dacom.sa.soilcorrection.Conversao.ConverteCMolcDm3EmMgDm3 {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    class edu.utfpr.cp.dacom.sa.soilcorrection.Conversao.ConverteKgHaEmK2O {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    class edu.utfpr.cp.dacom.sa.soilcorrection.Conversao.ConverteKgHaEmP2O5 {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    class edu.utfpr.cp.dacom.sa.soilcorrection.Conversao.ConverteMgDm3EmKgHa {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    class edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.CorrecaoCalcioMagnesio {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    class edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.CorrecaoFosforo {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    class edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.CorrecaoPotassio {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    class edu.utfpr.cp.dacom.sa.soilcorrection.EquilibrioCorrecaoCTC {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    enum FonteCalcioMagnesio {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    enum FonteFosforo {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    enum FontePotassio {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    interface edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.ICorrecaoNutriente {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    interface edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.ICorrecaoNutrienteQuantidadeAplicar {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    interface edu.utfpr.cp.dacom.sa.soilcorrection.Fonte_Nutriente.IFonteNutriente {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    enum NomeNutrienteAdicional {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    class edu.utfpr.cp.dacom.sa.soilcorrection.Nutriente.NutrienteAdicional {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    class edu.utfpr.cp.dacom.sa.soilcorrection.Nutriente.NutrientesCTC {
    }
  }
  

  namespace edu.utfpr.cp.dacom.sa.soilcorrection {
    enum TexturaSolo {
    }
  }
  

  edu.utfpr.cp.dacom.sa.soilcorrection.Conversao.ConverteCMolcDm3EmMgDm3 .up.|> edu.utfpr.cp.dacom.sa.soilcorrection.Conversao.Conversao
  edu.utfpr.cp.dacom.sa.soilcorrection.Conversao.ConverteKgHaEmK2O .up.|> edu.utfpr.cp.dacom.sa.soilcorrection.Conversao.Conversao
  edu.utfpr.cp.dacom.sa.soilcorrection.Conversao.ConverteKgHaEmP2O5 .up.|> edu.utfpr.cp.dacom.sa.soilcorrection.Conversao.Conversao
  edu.utfpr.cp.dacom.sa.soilcorrection.Conversao.ConverteMgDm3EmKgHa .up.|> edu.utfpr.cp.dacom.sa.soilcorrection.Conversao.Conversao
  edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.CorrecaoCalcioMagnesio .up.|> edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.ICorrecaoNutriente
  edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.CorrecaoFosforo .up.|> edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.ICorrecaoNutriente
  edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.CorrecaoFosforo .up.|> edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.ICorrecaoNutrienteQuantidadeAplicar
  edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.CorrecaoPotassio .up.|> edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.ICorrecaoNutriente
  edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.CorrecaoPotassio .up.|> edu.utfpr.cp.dacom.sa.soilcorrection.Correcao.ICorrecaoNutrienteQuantidadeAplicar
  edu.utfpr.cp.dacom.sa.soilcorrection.Fonte_Nutriente.FonteCalcioMagnesio .up.|> edu.utfpr.cp.dacom.sa.soilcorrection.Fonte_Nutriente.IFonteNutriente
  edu.utfpr.cp.dacom.sa.soilcorrection.Fonte_Nutriente.FonteFosforo .up.|> edu.utfpr.cp.dacom.sa.soilcorrection.Fonte_Nutriente.IFonteNutriente
  edu.utfpr.cp.dacom.sa.soilcorrection.Fonte_Nutriente.FontePotassio .up.|> edu.utfpr.cp.dacom.sa.soilcorrection.Fonte_Nutriente.IFonteNutriente
  edu.utfpr.cp.dacom.sa.soilcorrection.Nutriente.NutrienteAdicional o-- edu.utfpr.cp.dacom.sa.soilcorrection.Nutriente.NomeNutrienteAdicional : nome


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
